### ISSUE TITLE
[FIX] input fields are not responsive for smaller devices.

### ISSUE THREAD

**Issue by Chirayu31** [gdsc-ipsacademy/resume-builder#1]
**Problem:**
The current state of the project exhibits an issue where the input fields are not responsive. This affects the user experience, especially when accessing the application on different screen sizes, devices, or orientations.

**Expected Behavior:**
Input fields within the application should adapt to various screen sizes and orientations to provide a consistent and user-friendly experience. This includes responsiveness to different devices such as desktops, tablets, and mobile phones.

**Screenshots:**
![Screenshot 2023-10-05 201850](https://github.com/gdsc-ipsacademy/resume-builder/assets/29854558/42e79536-d2fd-4433-80dc-0ecbcaa30552)

**Comment by Sky-De** [comment]
@Chirayu31 hi there, i would like fix this issue, please assign this to me, i will start working on it as soon as i get assignment
Thanks

**Comment by Chirayu31** [comment]
@Sky-De go ahead, I'm assigning the to you!
