### ISSUE TITLE
[ENHANCEMENT] Improve button design

### ISSUE THREAD

**Issue by Chirayu31** [gdsc-ipsacademy/resume-builder#2]
**Problem:**
The current design of buttons in the project may not meet the desired aesthetic or usability standards. This issue proposes an enhancement to improve the button design to make them more visually appealing and user-friendly.

**Enhancement Goals:**

- Enhance the visual appeal of buttons to align with the overall project's design aesthetics.
- Improve button usability by making them more intuitive and accessible to users.
- Ensure consistency in button design across the application for a cohesive user experience.

**Comment by shubham-shinde-442** [comment]
I Would like to work on this issue, can u assign me?

**Comment by ismailbohra** [comment]
can you assign me this issue

**Comment by Chitraksh2005** [comment]
can you assign me in this issue

**Comment by Chirayu31** [comment]
@danishagarwal I'm assigning the issue to you!

**Comment by harshsharma-11** [comment]
@JustA3DObject @Chirayu31 if it is still open can i work on it

**Comment by harshsharma-11** [comment]
@JustA3DObject @Chirayu31 if it is still open can i work on it

**Comment by JustA3DObject** [comment]
> @JustA3DObject @Chirayu31 if it is still open can i work on it

It is still open. The last submitted PR had conflicts with main branch.

**Comment by harshsharma-11** [comment]
okk thanks for your reply ,please can you specify what's you want to achieve with this issue,more clarity about the issue

**Comment by danishagarwal** [comment]
Hi @JustA3DObject I have fixed the conflicts.

**Comment by JustA3DObject** [comment]
Thankyou for your contributions, I've been reviewing your PRs but @Chirayu31 is a little sick right now, so merges will take atleast 1-2 more days. 
Thanks again for resolving so many issues ^⁠_⁠^

Meanwhile, you can contribute to our other projects as well :⁠-⁠)

**Comment by harshsharma-11** [comment]
@JustA3DObject i would be happy to contribute to competetive programming ,can you provide what can be issues that need to be addressed there
