### ISSUE TITLE
The form accepts invalid email ID (Inefficient RegEx)

### ISSUE THREAD

**Issue by JustA3DObject** [gdsc-ipsacademy/resume-builder#24]
This is an invalid mail ID and is not accepted: 

![image](https://github.com/gdsc-ipsacademy/resume-builder/assets/81830617/f13aed34-e49c-4591-b324-54d3e1428ea6)

This also is an invalid email ID but this one is accepted: 

![image](https://github.com/gdsc-ipsacademy/resume-builder/assets/81830617/aa4497bc-2e0c-431b-a0bd-de0fafee9c88)

I'm guessing the problem lies in the [PersonalDetailsForm.js](https://github.com/gdsc-ipsacademy/resume-builder/blob/main/src/Components/PersonalDetailsForm.js) in `isValidEmail` function.

**Comment by waleedkhano** [comment]
Hello, @Chirayu31 May I work on this?
