### ISSUE TITLE
Feat: Change the Favicon and Title of the website

### ISSUE THREAD

**Issue by Abhishek9503** [gdsc-ipsacademy/resume-builder#30]

**Comment by harshsharma-11** [comment]
please assign me this issue

**Comment by harshsharma-11** [comment]
@Chirayu31 @Abhishek9503 please clarify

**Comment by harshsharma-11** [comment]
@JustA3DObject please clarify

**Comment by JustA3DObject** [comment]
> @JustA3DObject please clarify

I guess this issue is regarding the website icon and title. Right now on opening the site, it says "react app" and has react icon in the tab. You need to create a new icon (I guess?) and also update the title of the site and add it in the code.

**Comment by harshsharma-11** [comment]
okkk thanks,i am started working on this
