### ISSUE TITLE
[Feat]: Add the number of page opened and total no of pages 

### ISSUE THREAD

**Issue by Abhishek9503** [gdsc-ipsacademy/resume-builder#31]
Since this is page no 2 so add a tag to display the opened page and total pages in the website

![Screenshot (1423)](https://github.com/gdsc-ipsacademy/resume-builder/assets/103676667/4b5be1ca-5562-424c-89a7-e88916c63fac)

**Comment by harshsharma-11** [comment]
please assign this issue to me
