### ISSUE TITLE
use of this add buttons

### ISSUE THREAD

**Issue by harshsharma-11** [gdsc-ipsacademy/resume-builder#34]
there are buttons like add education these are of no use acc to me 

https://github.com/gdsc-ipsacademy/resume-builder/assets/138685168/ba6d84d5-1b3b-4b29-95f0-e72d144c081f

**Comment by JustA3DObject** [comment]
> there are buttons like add education these are of no use acc to me

Well they are actually useful if you want to add detailed info about your education. Like school, diploma, bachelors degree, masters degree etc.
Although I'd say that they are a bit confusing. If it was just a round "+" button, it'd have been much better.

**Comment by harshsharma-11** [comment]
@JustA3DObject should i change it do + button

**Comment by JustA3DObject** [comment]
@harshsharma-11 sure go ahead. Make sure the program runs perfectly before submitting a PR though, we currently don't have any integration tests.

**Comment by harshsharma-11** [comment]
okk sure

**Comment by harshsharma-11** [comment]
@JustA3DObject  @Chirayu31 if have some more issue you have addressed i can work on that too .Let me know if

**Comment by Chirayu31** [comment]
@harshsharma-11 ,

Thank you for your contribution. However, we have decided to not proceed with this change at the moment. Therefore, we will be closing this issue. Please focus on working on issues that are specifically assigned to you by me.

Thanks for your understanding.
